#include <stdio.h>
#include <conio.h>
#include <string.h>
#include <iostream.h>
int main()
{
int keaktifan,ujian,tugas,jumlah,hasil;
char nama[25];
cout<<"Nama Siswa     :";cin>>nama;
cout<<"Nilai Keaktifan     :";cin>>keaktifan;
cout<<"Nilai Tugas      :";cin>>tugas;
cout<<"Nilai Ujian     :";cin>>ujian;

cout<<"\n \n";

cout<<"Siswa YANG Bernama,";<<nama<<endl;
cout<<"Dengan Nilai Prestasi Yang Dihasilkan";
cout<<"Nilai Keaktifan *20%:";
cout<<"Nilai Tugas     *30%:";
cout<<"Nilai Ujian     *50%:";
cout<<"Jadi Siswa yang bernama";
cin>>nama<<endl;
cout<<"Memperoleh Nilai Akhir Sebesar";
getch();
}
